-d C:\Users\Gebruiker\Documents\Mij werks\FPGA\fpga-zx-spectrum\my_zx_spectrum_dram_video\impl\gwsynthesis\my_zx_spectrum_dram_video.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\Gebruiker\Documents\Mij werks\FPGA\fpga-zx-spectrum\my_zx_spectrum_dram_video\src\spectrum.cst
-cfg C:\Users\Gebruiker\Documents\Mij werks\FPGA\fpga-zx-spectrum\my_zx_spectrum_dram_video\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
